### ISSUE TITLE
Documentation LLDB-MI

### ISSUE THREAD

**Issue by NumberX** [0x55555555/lldb-example#1]
Hi,
I have to implement a graphical interface to open the Dump of Macos with LLDB.
I know how to do this using the command line, but this and less productive, I found that LLDB-MI little make me an interface to do this need but I did not find an example of LLDB-MI in C ++ and How to build LLDB-MI.
To detail our need:
1 - opening of a core dump.
2 -__ reading the value of a memory address.
3 -__ list threads and frames.
4 -__ get assembler of each frame.
  
Thank you in advance for your help.

**Comment by 0x55555555** [comment]
Sorry, beyond the example code in this repository, I have very little experience with lldb-mi.

You could try their mailing list?
